# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Ayou"
email = "arobcher233@163.com"
link = "https://github.com/Ayouuuu"
avatar = "/images/avatar.webp"
