pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - label=dependencies
      - check-success=Netlify / Redirect rules - ayou10031
    actions:
      merge:
        method: merge