pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - label=dependencies
      - check-success=netlify/ayou10031/deploy-preview
    actions:
      merge:
        method: merge