# example netlify.toml
[build]
  command = "hugo"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.101.0"

[[headers]]
  for = "*"
  [headers.values]
    cache-control = "max-age=604800"

[[headers]]
  for = "*.woff2"
  [headers.values]
    cache-control = "max-age=2592000"

[[headers]]
  for = "*.js"
  [headers.values]
    cache-control = "max-age=2592000"

[[headers]]
  for = "*.css"
  [headers.values]
    cache-control = "max-age=2592000"
