socks-port: 7891
redir-port: 7892
tproxy-port: 7893
mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: '127.0.0.1:9090'
secret: ''
routing-mark: 6666
hosts:
  dl.google.com: 180.163.151.161
  dl.l.google.com: 180.163.151.161
  update.googleapis.com: 180.163.151.161
dns:
  enable: true
  listen: '0.0.0.0:53'
  ipv6: false
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
proxies:
  - name: "azure"
    type: ssr
    server: # 服务器IP
    port: 7899 # 端口
    cipher: chacha20-ietf # 协议
    password: "" #密码
    obfs: plain
    protocol: origin
    udp: true
proxy-groups:
  -
    name: '🌐 国外流量'
    type: select
    proxies:
      - '♻️ 故障切换'
      - '➡️ 直接连接'
      - 'azure'
  -
    name: '🚥 其他流量'
    type: select
    proxies:
      - '🌐 国外流量'
      - '➡️ 直接连接'
  -
    name: '♻️ 故障切换'
    type: fallback
    proxies:
      - 'azure'
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  -
    name: '🎬 国际流媒体'
    type: select
    proxies:
      - '🌐 国外流量'
      - '➡️ 直接连接'
      - 'azure'
  -
    name: '🎬 大陆流媒体国际版'
    type: select
    proxies:
      - '➡️ 直接连接'
      - '🌐 国外流量'
      - 'azure'
  -
    name: '🎮 Steam'
    type: select
    proxies:
      - '🌐 国外流量'
      - '➡️ 直接连接'
      - 'azure'
  -
    name: '🌐 国际网站'
    type: select
    proxies:
      - '🌐 国外流量'
      - '➡️ 直接连接'
      - 'azure'
  -
    name: '🏠 大陆流量'
    type: select
    proxies:
      - '➡️ 直接连接'
      - '🌐 国外流量'
      - 'azure'
  -
    name: '🎬 大陆流媒体'
    type: select
    proxies:
      - '🏠 大陆流量'
      - '➡️ 直接连接'
      - 'azure'
  -
    name: '🏠 大陆网站'
    type: select
    proxies:
      - '🏠 大陆流量'
      - '➡️ 直接连接'
      - 'azure'
  -
    name: '➡️ 直接连接'
    type: select
    proxies:
      - DIRECT


rules:
  # > Google
  - DOMAIN-SUFFIX,blog.google,🌐 国际网站
  # - DOMAIN-SUFFIX,googletraveladservices.com,🌐 国际网站
  - DOMAIN,clientservices.googleapis.com,🌐 国际网站
  # - DOMAIN,dl.google.com,🌐 国际网站
  # - DOMAIN,dl.l.google.com,🌐 国际网站
  # - DOMAIN,update.googleapis.com,🌐 国际网站
  - DOMAIN,translate.googleapis.com,🌐 国际网站
  # >> Google Fonts API
  - DOMAIN,fonts.googleapis.com,🌐 国际网站
  - DOMAIN,fonts.gstatic.com,🌐 国际网站
  # >> Firebase Cloud Messaging
  - DOMAIN,mtalk.google.com,🌐 国际网站
  - DOMAIN,alt1-mtalk.google.com,🌐 国际网站
  - DOMAIN,alt2-mtalk.google.com,🌐 国际网站
  - DOMAIN,alt3-mtalk.google.com,🌐 国际网站
  - DOMAIN,alt4-mtalk.google.com,🌐 国际网站
  - DOMAIN,alt5-mtalk.google.com,🌐 国际网站
  - DOMAIN,alt6-mtalk.google.com,🌐 国际网站
  - DOMAIN,alt7-mtalk.google.com,🌐 国际网站
  - DOMAIN,alt8-mtalk.google.com,🌐 国际网站
  # >> Paramount+
  # - DOMAIN,pubads.g.doubleclick.net,🌐 国际网站

  # Unbreak
  - RULE-SET,Unbreak,DIRECT

  # Global Area Network

  # (Streaming Media)
  - RULE-SET,Streaming,🎬 国际流媒体

  # (StreamingSE)
  - RULE-SET,StreamingSE,🎬 大陆流媒体国际版

  # (Steam)
  - RULE-SET,Steam,🎮 Steam

  # (DNS Cache Pollution) / (IP Blackhole) / (Region-Restricted Access Denied) / (Network Jitter)
  - RULE-SET,Global,🌐 国际网站

  # (StreamingCN)
  - RULE-SET,StreamingCN,🎬 大陆流媒体

  # China Area Network
  - RULE-SET,China,🏠 大陆网站

  # Local Area Network
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT

  # （可选）使用来自 ipipdotnet 的 ChinaIP 以解决数据不准确的问题，使用 ChinaIP.yaml 时可禁用下列直至（包括）「GEOIP,CN」规则
  - RULE-SET,ChinaIP,🏠 大陆流量
  # Tencent
  # - IP-CIDR,119.28.28.28/32,🏠 大陆流量
  # - IP-CIDR,182.254.116.0/24,🏠 大陆流量
  # GeoIP China
  # - GEOIP,CN,🏠 大陆流量

  - MATCH,🚥 其他流量

rule-providers:
# name: # Provider 名称
#   type: http # http 或 file
#   behavior: classical # 或 ipcidr、domain
#   path: # 文件路径
#   url: # 只有当类型为 HTTP 时才可用，您不需要在本地空间中创建新文件。
#   interval: # 自动更新间隔，仅在类型为 HTTP 时可用

  Unbreak:
    type: http
    behavior: classical
    path: ./RuleSet/Unbreak.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml
    interval: 86400

  Streaming:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/Streaming.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400

  StreamingSE:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingSE.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
    interval: 86400

  StreamingCN:
    type: http
    behavior: classical
    path: ./RuleSet/StreamingMedia/StreamingCN.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingCN.yaml
    interval: 86400

  Steam:
    type: http
    behavior: classical
    path: ./RuleSet/Extra/Game/Steam.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Game/Steam.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    path: ./RuleSet/Global.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    path: ./RuleSet/China.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml
    interval: 86400

  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./RuleSet/Extra/ChinaIP.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
    interval: 86400